language: python

python:
    - 2.7

env:
    matrix:
        - OSCAR="django-oscar>=0.4,<0.5"
        - OSCAR="django-oscar>=0.5,<0.6"
        - OSCAR="django-oscar>=0.6,<0.7"
        - OSCAR="django-oscar>=0.7,<0.8"

install:
    - make install
    - pip install $OSCAR

script:
    - py.test
